source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-gist'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'
gem 'jekyll-paginate'
gem 'csv'
gem 'base64'
gem 'jekyll-spaceship'
gem "jekyll-target-blank", "~> 2.0"
